### ISSUE TITLE
libfont-freetype-perl: FTBFS on many architectures

### ISSUE THREAD

**Issue by gregoa** [zmughal/p5-Font-FreeType#17]
We have the following bug reported to the Debian package of
Font-FreeType (https://bugs.debian.org/799888):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Source: libfont-freetype-perl
Version: 0.06-1

It's failing to build on architectures with plain char unsigned:

https://buildd.debian.org/status/package.php?p=libfont-freetype-perl&suite=sid

A couple of tests are failing:

not ok 601 - no fallback glyph
not ok 603 - missing glyph has horizontal advance

I think the corresponding code is lines 197-202 here:

https://sources.debian.net/src/libfont-freetype-perl/0.06-1/t/10metrics_verasans.t/

In both cases there is a call to glyph_from_char with the first
argument a non-ASCII character, 'Ë'.

This is not supposed to work, according to line 21 here:

https://sources.debian.net/src/libfont-freetype-perl/0.06-1/TODO/

Line 808 of 
https://sources.debian.net/src/libfont-freetype-perl/0.06-1/FreeType.xs/
might be the implementation of how the char is converted:

char_code = *str;

If that's it, it's no surprise that it doesn't work on non-ASCII
characters. Presumably the tests pass by accident on architectures
where plain char is signed.

You could just disable the failing tests, though it probably wouldn't
be hard to make glyph_from_char work properly.


```
------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by basiliscos** [comment]
Thank you for bugreport!

Could you, please, do test the new build (https://metacpan.org/release/DMOL/Font-FreeType-0.07_1)

WBR,
basiliscos

**Comment by gregoa** [comment]
On Wed, 23 Sep 2015 15:06:41 -0700, Ivan Baidakou wrote:

> Thank you for bugreport!
> Could you, please, do test the new build (https://metacpan.org/release/DMOL/Font-FreeType-0.07_1)

Thanks for the super-fast commits!
I've uploaded 0.07_2 to Debian/unstable right now; lets see what the
build daemons say:
https://buildd.debian.org/status/logs.php?pkg=libfont-freetype-perl&ver=0.07~2-1

Cheers,
gregor

-- 
 .''`.  Homepage: http://info.comodo.priv.at/ - OpenPGP key 0xBB3A68018649AA06
 : :' : Debian GNU/Linux user, admin, and developer -  https://www.debian.org/
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Alannah Myles

**Comment by gregoa** [comment]
Looks good, no build failures so far, and especially the architectures with problems are already done.
(Some slow non-release architectures are still missing from https://buildd.debian.org/status/package.php?p=libfont-freetype-perl but I guess we can assume the problem is fixed.)

**Comment by basiliscos** [comment]
Thank you too!
